env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  chrome: false
parserOptions:
  sourceType: module
rules:
  indent:
    - 2
    - tab
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
